version: '3.8'

services:
  core-backend:
    build:
      context: ./services/core
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/resumeai
      - JWT_SECRET=your-jwt-secret
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    depends_on:
      - db
    volumes:
      - ./services/core:/app
      - /app/node_modules
    networks:
      - resumeai-network

  ai-interview:
    build:
      context: ./services/ai-interview
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - CORE_SERVICE_URL=http://core-backend:3000
    depends_on:
      - core-backend
    volumes:
      - ./services/ai-interview:/app
      - /app/.venv
    networks:
      - resumeai-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resumeai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - resumeai-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - core-backend
      - ai-interview
    networks:
      - resumeai-network

volumes:
  postgres_data:

networks:
  resumeai-network:
    driver: bridge